### ISSUE TITLE
variable delay_to_inf missing

### ISSUE THREAD

**Issue by m-bob** [adamkucharski/2020-cov-tracing#12]
Hi Adam!

Thanks so much for the paper, for the data, and for this code!

When I tried to run it, I got a message that the object "delay_to_inf" is missing.

How do I set that variable? (When I make something up for it, the code seems to run ok -- so there are probably no other issues.)

Thanks!

Murray

**Comment by adamkucharski** [comment]
Code is currently work-in-progress, but should be fixed shortly.

**Comment by m-bob** [comment]
Thank you for replying and fixing the issues so quickly!

The code works with no issues for me! (I'm using the latest R version (4.0.0) on a 2015 Macbook Pro (retina, 13", 2 cores) and the code runs in significantly under a minute.)
