### ISSUE TITLE
Use of T/F (minor)

### ISSUE THREAD

**Issue by seabbs** [adamkucharski/2020-cov-tracing#2]
T/F can be overwritten by users (but why would they) to mean something other than `TRUE/FALSE` would be better to use in full for safety/style.

**Comment by pearsonca** [comment]
alternative opinion: comparison to either T/F or TRUE/FALSE is code smell. These are all intended to be logicals; use them as such.

**Comment by adamkucharski** [comment]
Thanks for flagging, but think OK to leave as is.
