### ISSUE TITLE
tidyverse dependency (minor/reproducibility)

### ISSUE THREAD

**Issue by seabbs** [adamkucharski/2020-cov-tracing#6]
They tidyverse is now well over 60+ packages. When developing analysis it makes sense to use for ease but can make reproducibility a challenge as it doesn't make clear what is actually a dependency. It would be much better to just list packages actually used (based on the functions script this looks like: `dplyr`, `tibble`, `readr` and `magrittr`)

**Comment by adamkucharski** [comment]
Good suggestion, have edited.
