### ISSUE TITLE
Work directory setting (minor/reproducibility) 

### ISSUE THREAD

**Issue by seabbs** [adamkucharski/2020-cov-tracing#7]
This is very minor as it looks like this is just one call in one function but in general, would be better to leave this to the usage instructions (i.e where do you need to be when using the analysis). I like the `here` package but this is very much optional.

**Comment by pearsonca** [comment]
agree with substance, though prefer run script from command line + `commandArgs(...)` style approach, rather than relying on `here`.

**Comment by adamkucharski** [comment]
Ok, will pull out path and put in readme.
